spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/web_chat?user=root&serverTimezone=UTC&characterEncoding=UTF-8
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    template-loader-path: classpath:/templates/
    prefix: /chat/
    suffix: .ftl
    contentType: text/html
    charset: UTF-8
    cache: false
